shared:
  model_path: OpenGVLab/InternVL3-8B-HF
  model_type: internvl
  OPENROUTER_API_KEY: 
  with_tag: true
  vision_token_id: 151667
  patch_size: 14
  merge_size: 2
  layers_num: 28
  heads_num: 28
  
generator:
  max_new_tokens: 1024
  overwrite: false
  disable_monkey_patch: true
  outlier_ratio: 50.0
  dominance_ratio: 5.0
  outlier_share_thr: 0.3

evaluator:
  global_save_fig: true
  normal_set_zero: false
  overwrite: false
  return_aggregate: true
  attention_eval_mode: sink_first
  topk_spike_patches: 3
